POST https://auth-backend-production-054a.up.railway.app/api/v1/auth/signup
Content-Type: application/json

{
    "name":"Utkarsh Singh",
    "email":"admin@tecrun.tech",
    "password": "150783Pn@"
}
###
POST https://auth-backend-production-054a.up.railway.app/api/v1/auth/verify
Content-Type: application/json

{
    "otp":524957,
    "email":"admin@tecrun.tech"
}

###
POST https://auth-backend-production-054a.up.railway.app/api/v1/auth/send-otp
Content-Type: application/json

{
    "email":"usjadon19@gmail.com"
}

###

POST https://auth-backend-production-054a.up.railway.app/api/v1/auth/login
Content-Type: application/json

{
    "email":"whataboutadate@gmail.com",
    "password": "150783Pn@"
}
###

POST https://auth-backend-production-054a.up.railway.app/api/v1/auth/reset
Content-Type: application/json

{
    "otp": 775481,
    "email":"usjadon19@gmail.com",
    "new_password":"Harsh16@auth"
}

### 
GET https://auth-backend-production-054a.up.railway.app/api/v1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3aGF0YWJvdXRhZGF0ZUBnbWFpbC5jb20iLCJzdWIiOiJBQ0NFU1MiLCJleHAiOjE2NzIxNDM1NDV9.gqqqqc9-m_E8Y_QKuU3TFisBWLF2TcEjs0jzvcE8fFY